# Building custom mapper example from Legion examples.
#
# We use it as a useful test harness for our build script.

EXEC = parallelism-kinds

SRCS = parallelism-kinds.rg parallelism-kinds-map.cc

LIBRARY = parallelism-kinds

include ../../libs/scripts/build-rules.mk
