#!/bin/sh
DA=~/.cabal/bin/ddp-erlang-style-SIMD-eventlog
cp $DA slave1
cp $DA slave2
cp $DA slave3
cp $DA slave4
cp $DA slave5
cp $DA master

./slave1 slave --ip localhost --port 60001 +RTS -l-au &
./slave2 slave --ip localhost --port 60002 +RTS -l-au &
./slave3 slave --ip localhost --port 60003 +RTS -l-au &
./slave4 slave --ip localhost --port 60004 +RTS -l-au &
./slave5 slave --ip localhost --port 60005 +RTS -l-au &
sleep 1
./master master --ip localhost --port 44440 +RTS -l-au
rm -f master slave1 slave2 slave3 slave4 slave5
ghc-events show slave1.eventlog >slave1.eventlog.txt
ghc-events show slave2.eventlog >slave2.eventlog.txt
ghc-events show slave3.eventlog >slave3.eventlog.txt
ghc-events show slave4.eventlog >slave4.eventlog.txt
ghc-events show slave5.eventlog >slave5.eventlog.txt
ghc-events show master.eventlog >master.eventlog.txt
