# Building custom mapper example from Legion examples.
#
# We use it as a useful test harness for our build script.

EXEC = 	cuastom-mapper-example

SRCS = custom_mapper.cc

include ../../../libs/scripts/makefile.inc
