# Building custom mapper example from Legion examples.
#
# We use it as a useful test harness for our build script.

EXEC = static-scheduling

SRCS = static-scheduling.rg static-scheduling-support.cc

include ../../libs/scripts/build-rules.mk
