# Building custom mapper example from Legion examples.
#
# We use it as a useful test harness for our build script.

EXEC = bisectional-bandwidth

SRCS = bisectional-bandwidth.cc

include ../../../libs/scripts/build-rules.mk
