# Building custom mapper example from Legion examples.
#
# We use it as a useful test harness for our build script.

EXEC = bandwidth-latency

LIBRARY = bandwidth-latency-support

SRCS = bandwidth-latency.rg bandwidth-latency-support.cc

include ../../libs/scripts/build-rules.mk
