#!/bin/bash

# Runner script for MS7 programs.

# Parse command line.
# Parsing command line args.
nodes=1
tasks=1
net=""
mem=""
gpu=""
threads=1
program=$0
usage="usage: $0 [-[-]nodes=nodes to use] [-[-]tasks=tasks to run] [-[-]threads=CPU cores to allocate per task] [-[-]mem=MB per task] [--] [other arguments]"
while (($#)); do
    arg=$1
    case $arg in
        -nodes=*|--nodes=*)
            nodes="${arg#*=}"
            shift
            ;;
        -tasks=*|--tasks=*)
            tasks="${arg#*=}"
            shift
            ;;
        -net=*|--net=*)
            net="${arg#*=}"
            shift
            ;;
        -threads=*|--threads=*)
            threads="${arg#*=}"
            shift
            ;;
        -mem=*|--mem=*)
            mem="${arg#*=}"
            shift
            ;;
        -gpu=*|--gpu=*)
            gpu="${arg#*=}"
            shift
            ;;
        -time=*|--time=*)
            time="${arg#*=}"
            shift
            ;;
        -h|--help)
            echo $usage
            exit 1
            ;;
        --)
            shift
            break
            ;;
        -*)
            echo "invalid option $arg"
            echo "(use -- to delimite launcher and program arguments)"
            echo ""
            echo $usage
            exit 1
            ;;
        *)
            break
            ;;
    esac
done
program_args="$*"

# Execute command
function run {

    # Export two variables for command and arguments. They will be used in the
    # SLURM and amudprun launchers below.
    export SDP_LAUNCH_COMMAND="$1"
    export SDP_LAUNCH_ARGUMENTS="$program_args"
    export SDP_MEM_LIMIT="$mem"

    cmdline="$program $program_args"
    # Select between srun/amudprun.
    case "$net" in
        ibv)
            if [ -n "$mem" ] ; then
                cmdline="--mem-per-cpu=$mem $cmdline"
            fi
            if [ -n "$gpu" ] ; then
                # XXX is it right way?
                cmdline="--gres=$gpu $cmdline"
            fi
            sbatch --nodes=$nodes --ntasks=$tasks --cpus-per-task=$threads --time=$time $SDP_SCRIPT_DIR/slurm_submit.wilkes.sdp
            ;;
        "")
            # Check arguments for local run.

            # nodes == 1
            if [ "$nodes" -ne "1" ] ; then
                echo "number of nodes for local run should be 1."
                exit 1
            fi

            # setup env for amudprun.
            export CSPAWN_CMD="$SDP_SCRIPT_DIR/custom_spawner %N %C"

            # Execute!
            $SDP_BUILDDIR/gasnet/release/bin/amudprun -n $tasks -spawn L $program-local $program_args
            ;;
        *)
            echo "invalid net '$net'"
            exit 1
            ;;
    esac
}

# Add invocation of run here.
