#!/bin/bash

# Runner script for MS7 programs.

# Parse command line.
# Parsing command line args.
nodes=1
tasks=1
net=""
mem=""
threads=1
usage="usage: $0 [-[-]nodes=nodes to use] [-[-]tasks=tasks to run] [-[-]threads=CPU cores to allocate per task] [-[-]mem=MB per task] [--] [other arguments]"
while (($#)); do
    arg=$1
    case $arg in
        -nodes=*|--nodes=*)
            nodes="${arg#*=}"
            shift
            ;;
        -tasks=*|--tasks=*)
            tasks="${arg#*=}"
            shift
            ;;
        -net=*|--net=*)
            net="${arg#*=}"
            shift
            ;;
        -threads=*|--threads=*)
            threads="${arg#*=}"
            shift
            ;;
        -mem=*|--mem=*)
            mem=="${arg#*=}"
            shift
            ;;
        -h|--help)
            echo $usage
            exit 1
            ;;
        --)
            shift
            break
            ;;
        -*)
            echo "invalid option $arg"
            echo "(use -- to delimite RT and program arguments)"
            echo ""
            echo $usage
            exit 1
            ;;
        *)
            break
            ;;
    esac
done

# Execute command
function run {
    # Select between srun/amudprun.
    case "$net" in
        )
            echo "running with amudprun"
            ;;
        ibv)
            echo "running with IB."
            ;;
        *)
            echo "invalid net '$net'"
            exit 1
            ;;
    esac
}

# Add invocation of run here.
