# Building custom mapper example from Legion examples.
#
# We use it as a useful test harness for our build script.

EXEC = resource-management

SRCS = resource-management.cc

include ../../libs/scripts/build-rules.mk
