# Building custom mapper example from Legion examples.
#
# We use it as a useful test harness for our build script.

EXEC = resource-management

SRCS = resource-nanagement.cc

include ../../../libs/scripts/makefile.inc
