# Building custom mapper example from Legion examples.
#
# We use it as a useful test harness for our build script.

EXEC = index_tasks

SRCS = index_tasks.rg report.cc

LIBRARY = report

CXX_FLAGS += --std=c++11
CC_FLAGS += --std=c++11

include ../../libs/scripts/build-rules.mk
