# Building custom mapper example from Legion examples.
#
# We use it as a useful test harness for our build script.

EXEC = scalability-bandiwdth

SRCS = scalability-bandiwdth.rg scalability-bandiwdth-map.cc

include ../../../libs/scripts/build-rules.mk
