# Makefile to build Regent programs.

# Define the executable name.
EXEC = slurm

# Include the script for rules "exec" (default, build the executable" and "clean".
include ../../libs/scripts/build-rules.mk