# Building custom mapper example from Legion examples.
#
# We use it as a useful test harness for our build script.

EXEC = hdf_attach

SRCS = hdf_attach.cc

CC_FLAGS += -I/usr/include/hdf5/serial

include $(SDP_SCRIPT_DIR)/cluster_build_rules.mk
