# Building custom mapper example from Legion examples.
#
# We use it as a useful test harness for our build script.

EXEC = hdf5-access

SRCS = hdf5-access.cc

include ../../libs/scripts/build-rules.mk
