# Makefile to build Regent programs.

# Define the executable name.
EXEC = choice

SRCS = choice.rg

# Include the script for rules "exec" (default, build the executable" and "clean".
include $(SDP_SCRIPT_DIR)/cluster_build_rules.mk